# Project: ogreproject
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -L"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/lib/release" -L"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/lib/release/opt" -mwindows  OgreSDK_MinGW_v1-8-1/lib/release/libOgreMain.dll.a OgreSDK_MinGW_v1-8-1/lib/release/libOgrePaging.dll.a OgreSDK_MinGW_v1-8-1/lib/release/libOgreProperty.dll.a OgreSDK_MinGW_v1-8-1/lib/release/libOgreRTShaderSystem.dll.a OgreSDK_MinGW_v1-8-1/lib/release/libOgreTerrain.dll.a OgreSDK_MinGW_v1-8-1/lib/release/libOIS.dll.a  OgreSDK_MinGW_v1-8-1/lib/release/opt/libPlugin_CgProgramManager.dll.a OgreSDK_MinGW_v1-8-1/lib/release/opt/libPlugin_OctreeSceneManager.dll.a  OgreSDK_MinGW_v1-8-1/lib/release/opt/libPlugin_ParticleFX.dll.a   OgreSDK_MinGW_v1-8-1/lib/release/opt/libRenderSystem_GL.dll.a OgreSDK_MinGW_v1-8-1/lib/release/opt/libPlugin_OctreeZone.dll.a   OgreSDK_MinGW_v1-8-1/lib/release/opt/libPlugin_PCZSceneManager.dll.a -m32
INCS     = -I"C:/Program Files/Dev-Cpp/MinGW64/include" -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/include" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/include/OGRE" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/boost/boost" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/boost" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/Samples/Common/include" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/include/OIS"
CXXINCS  = -I"C:/Program Files/Dev-Cpp/MinGW64/include" -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/include" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/include/OGRE" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/boost/boost" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/boost" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/Samples/Common/include" -I"C:/Users/Luke/Desktop/ogre/ogre.1.8.1/OgreSDK_MinGW_v1-8-1/include/OIS"
BIN      = ogreproject.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
